DistroLab2/Controllers/MessageController.cs
using DistroLab2.Areas.Identity.Models;
using DistroLab2.Models;
using DistroLab2.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace DistroLab2.Controllers
{
    /// <summary>
    /// Controller used for the application
    /// </summary>
    [Authorize]
    public class MessageController : Controller
    {
        
        private readonly UserManager<LoginUser> _userManager;
        private readonly MessageLogic _messageLogic;
        private readonly UserLogic _userLogic;

        public MessageController( UserManager<LoginUser> userManager)
        {
            _userManager = userManager;
            _messageLogic = new MessageLogic(userManager);
            _userLogic = new UserLogic(userManager);
        }
        /// <summary>
        /// Returns the home page with login info for the logged in user
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            String userId = _userManager.GetUserId(User);
            IndexViewModel indexViewModel = _userLogic.GetLoginDetails(userId);
            return View(indexViewModel);
        }

        /// <summary>
        /// Returns the list of messages from a given sender to the logged in user
        /// </summary>
        /// <param name="userName"></param>
        /// <returns></returns>
        // GET: Message
        public IActionResult MessageList(String userName)
        {
            var recipantName = _userManager.GetUserName(User);
            List<MessageViewModel> messages = _messageLogic.GetMessagesFromSenderToRecipant(userName, recipantName);
            return View(messages);
        }
        /// <summary>
        /// Returns all the info for a given message, given that it is sent to the logged in user
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Message/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            String userId = _userManager.GetUserId(User);
            var message = _messageLogic.GetMessage(id, userId);
            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        /// <summary>
        /// Returns the view used to create and send a message
        /// </summary>
        /// <returns></returns>
        // GET: Message/Send
        public IActionResult Send()
        {    
            SendFormViewModel model = new SendFormViewModel();
            model.Users = _userLogic.GetAllUsers();
            return View(model);
        }
        /// <summary>
        /// Sends the message to the given recipant
        /// </summary>
        /// <param name="messageViewModel"></param>
        /// <returns></returns>
        // POST: Message/Send
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Send([Bind("Recipant,Title,Content")] MessageViewModel messageViewModel)
        {
 
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                var timeSent = DateTime.Now;
                _messageLogic.CreateMessage(messageViewModel, userId, timeSent);
                TempData["confirmData"] = "The message has been sent to " + messageViewModel.Recipant + ", " + timeSent;
                return RedirectToAction(nameof(Send));
            }
            TempData["confirmData"] = "";
            return RedirectToAction(nameof(MessageList));
        }
        /// <summary>
        /// Returns delete window with message info, given that the message is sent to the logged in user
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Message/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            String userId = _userManager.GetUserId(User);
            var message = _messageLogic.GetMessage(id, userId);

            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        /// <summary>
        /// Deletes the given message
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // POST: Message/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            String userId = _userManager.GetUserId(User);
            var message = _messageLogic.GetMessage(id, userId);
            _messageLogic.Deletemessage(id, userId);
            
            return RedirectToAction(nameof(MessageList), new { userName = message.Sender});
        }

        /// <summary>
        /// Returns the view of the inbox with user that has sent messages to the logged in user
        /// </summary>
        /// <returns></returns>
        // GET: Inbox
        public async Task<IActionResult> Inbox()
        {
            var userId = _userManager.GetUserId(User);
            ReadViewModel readViewModel = _messageLogic.GetInbox(userId);
            return View(readViewModel);
        }
    }
}

DistroLab2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Message app</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Message" asp-action="Index">Message app</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Message" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Message" asp-action="Inbox">Inbox</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Message" asp-action="Send">Send message</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>